default: &default
  adapter: postgresql 
  encoding: utf8
  hostname: localhost -h 127.0.0.1
  pool: 5
  username: feed_reader 
  password: 
  timeout: 5000

development:
  <<: *default
  database: feed_reader_development 

test:
  <<: *default
  database: feed_reader_test 
