default: &default
  adapter: postgresql 
  encoding: utf8
  pool: 5
  username: peady
  password:
  timeout: 5000

development:
  <<: *default
  database: feed_reader_development 

test:
  <<: *default
  database: feed_reader_test 
